version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./01-pagila-schema.sql:/docker-entrypoint-initdb.d/01-pagila-schema.sql
      - ./02-pagila-data.sql:/docker-entrypoint-initdb.d/02-pagila-data.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080